all: Server Client ClientThread Face

Server: Server.java
	javac Server.java
    
Client: Client.java
	javac Client.java
    
ClientThread: ClientThread.java
	javac ClientThread.java

Face: Face.java
	javac Face.java
